### ISSUE TITLE
Issue with run.sh script location

### ISSUE THREAD

**Issue by bhidalto** [GoogleCloudPlatform/dataproc-custom-images#14]
I have found an issue when trying to create a Dataproc custom image when following the Google Cloud Platform documentation[1]. 

**Error Logs**

```
[Daisy] Errors in one or more workflows:
  debian-error: FileIOError: stat /home/$USER/dataproc-custom-image/dataproc-custom-images/custom_image_utils/startup_script/run.sh: no such file or directory
Traceback (most recent call last):
  File "generate_custom_image.py", line 110, in <module>
    main()
  File "generate_custom_image.py", line 101, in main
    daisy_image_creator.create(args)
  File "/home/borjah/dataproc-custom-image/dataproc-custom-images/custom_image_utils/daisy_image_creator.py", line 43, in create
    os.path.abspath(args.daisy_path), workflow_script)
  File "/home/$USER/dataproc-custom-image/dataproc-custom-images/custom_image_utils/daisy_workflow_executor.py", line 42, in run
    raise RuntimeError("Error building custom image.")
RuntimeError: Error building custom image.
```

**Steps to reproduce error**

Executing the commands from the Google Clound Console ,these are the steps I followed in order to reproduce the error:

- Cloned the repo: ```git clone https://github.com/GoogleCloudPlatform/dataproc-custom-images.git```
- Moved to the custom images folder: ```cd dataproc-custom-images```
- Enabled the Cloud Dataproc API, Compute Engine API, and Cloud Storage APIs.
- Download daisy bin: ```wget https://storage.googleapis.com/compute-image-tools/release/linux/daisy```
- Give daisy binary file execution permission: ```chmod +x daisy```
- Created a Cloud Storage Bucket
- Created initialisation script with the following commands inside:
 ```
   #! /usr/bin/bash
   apt-get -y update
   apt-get install python-dev -y
   apt-get install python-pip -y
   pip install numpy
 ```
 
- Execute the image creation command: 
```python generate_custom_image.py --image-name custom-image-error --dataproc-version 1.4.7-debian9 --customization-script initialisation.sh --zone europe-west1-c --gcs-bucket gs://mybucket --daisy-path daisy```

**Workaround**

As we can see in the error logs when executing the command, the create image script is looking for a script named “run.sh” but it does in the path custom_image_utils/startup_script/run.sh.
There is indeed a script named “run.sh” but not in this path, so the workaround is to make a folder called “startup_script” inside the folder “custom_image_utils” and copy the script run.sh that is located inside dataproc-custom-images/startup_script/run.sh

In order to solve this error follow next steps from the dataproc-custom-images base folder:

Create startup_script folder inside custom_image_utils:
```mkdir custom_image_utils/startup_script```

Copy run.sh from the startup_script folder into the newly created folder custom_image_utils_startup_script 
```cp startup_script/run.sh custom_image_utils/startup_script/```
_______________________________
[1] https://cloud.google.com/dataproc/docs/guides/dataproc-images

**Comment by functicons** [comment]
@bhidalto thanks for the feedback, we'll fix it. We are deprecating Daisy, a workaround now is run the command without the `--daisy-path` flag.
