### ISSUE TITLE
Shell script executor assumes linux style bash path

### ISSUE THREAD

**Issue by hazelj** [GoogleCloudPlatform/dataproc-custom-images#18]
`shell_script_executor.py` assumes `/usr/bin/bash` for the bash location, but this breaks on the default install in osx and fails with deceptive error message that may lead the user to believe the tempfile is the issue. Easy to soft link locally, but probably worth considering.

https://github.com/GoogleCloudPlatform/dataproc-custom-images/blob/master/custom_image_utils/shell_script_executor.py#L37

**Comment by functicons** [comment]
hazelj@, Thanks for the feedback! I'm actually not familiar with OSX. Do you know if replacing `/usr/bin/bash` with `bash` works on osx?

**Comment by hazelj** [comment]
@functicons apologies on my delayed reply, but yes, I changed it to just `bash` locally to get by, and that should work on all/most OSX dists, as far as I know. Thanks for the response and the change!
