### ISSUE TITLE
Not Able To Create A Custom Image On MacOS 10.14.5, Python 2.7

### ISSUE THREAD

**Issue by markcb2** [GoogleCloudPlatform/dataproc-custom-images#27]
Not able to create a Google Cloud custom dataproc image using MacOS 10.14.5, Google Cloud SDK 266.0.0 and gsutil 4.44.

The generate_custom_image.py script generates an error when it tries to run my custom script.  

**

> Building synchronization state...
> Starting synchronization...
> Copying file:///tmp/custom-image-custom_python_1_4_14_debian9-20191009-140050/logs/workflow.log [Content-Type=text/plain]...
> - [1/1 files][  294.0 B/  294.0 B] 100% Done                                    
> Operation completed over 1 objects/294.0 B.                                      
> + [[ -f /tmp/custom-image-custom_python_1_4_14_debian9-20191009-140050/image_created ]]
> + echo -e 'Workflow failed, check logs at /tmp/custom-image-custom_python_1_4_14_debian9-20191009-140050/logs/ or gs://bucket-mcberma/custom-image-custom_python_1_4_14_debian9-20191009-140050/logs/'
> Workflow failed, check logs at /tmp/custom-image-custom_python_1_4_14_debian9-20191009-140050/logs/ or gs://bucket-mcberma/custom-image-custom_python_1_4_14_debian9-20191009-140050/logs/
> + exit 1
> Traceback (most recent call last):
>   File "generate_custom_image.py", line 95, in <module>
>     main()
>   File "generate_custom_image.py", line 88, in main
>     shell_image_creator.create(args)
>   File "/Users/mcberma/opensource/dataproc-custom-images-master/custom_image_utils/shell_image_creator.py", line 43, in create
>     shell_script_executor.run(script)
>   File "/Users/mcberma/opensource/dataproc-custom-images-master/custom_image_utils/shell_script_executor.py", line 47, in run
>     raise RuntimeError("Error building custom image.")
> RuntimeError: Error building custom image

**

I have validated that the custom script does not have any carriage returns or extraneous characters.

Here is how I am executing the python script

> python generate_custom_image.py --image-name custom_python_1_4_14_debian9 --dataproc-version 1.4.14-debian9 --customization-script custom_image.sh --zone us-central1-a --gcs-bucket gs://zzzzz-zzzzz

I have attached the custom script file and the workflow log. 

[workflow.log](https://github.com/GoogleCloudPlatform/dataproc-custom-images/files/3709048/workflow.log)

[custom_image.sh.zip](https://github.com/GoogleCloudPlatform/dataproc-custom-images/files/3709087/custom_image.sh.zip)

**Comment by medb** [comment]
Hm, this must be shell incompatibility. May you post output of `sh -version` command?

**Comment by markcb2** [comment]
GNU bash version 3.2.57(1)-release (x86_64-apple-darwin18)

Sent from my iPhone

**Comment by medb** [comment]
Yeah, associative arrives supported only in Bash 4, you need to upgrade your MacOS Bash to make it work.
