### ISSUE TITLE
Unreliable behavior in step wait-for-install prevents built image to be recognized as successfully created

### ISSUE THREAD

**Issue by lukeFalsina** [GoogleCloudPlatform/dataproc-custom-images#32]
Hello,

I am experiencing a odd behavior when attempting to build a custom image where less or more frequently the Daisy controller will fail to recognize that an image has successfully reached the end of the custom image script installation and just halts indefinitely (until the 2h timeout is reached and the build fails). To me this looks like a failure in matching the successful string on the serial port of the VM.

Notice this does not happen every time but a considerable amount of times to make this very annoying and not allowing to build images reliably (as I'm rerunning the same build command with the same custom script and sometimes the outcome is a failure and sometimes it is not).

My invocation looks like the following:
```
python2.7 ${BUILDER_ROOT}/cloud-dataproc/custom-images/generate_custom_image.py \
    --service-account ${SERVICE_ACCOUNT} \
    --image-name my-custom-image \
    --dataproc-version 1.3.5 \
    --customization-script ${CUSTOM_INIT_ACTION} \
    --daisy-path ${DAISY_PATH} \
    --zone europe-west1-b \
    --gcs-bucket ${GCS_BUCKET_IN_MY_PROJECT} \
    --project-id ${MY_PROJECT_ID} \
    --subnetwork projects/${MY_NET_HOST_PROJECT}/regions/europe-west1/subnetworks/${MY_SHARED_VPC_NAME} \
    --disk-size 20 \
    --no-smoke-test
```

A few notes on the invocation above:
- ${SERVICE_ACCOUNT} is a SA in my project with the following roles set in IAM (Compute Admin and Editor). I also tried to remove/modify the IAM roles but in any case the pipeline fails with the same outcome (image installation hanging). Open question: What is the minimal set of permissions needed for the SA of the VM execution the custom script? I would really love to drop that Editor role..
- ${DAISY_PATH} points to a Daisy executable, specifically the one coming from the latest commit on master of the Daisy repository (I can't use the release version as I want to use a shared VPC as subnetwork and that commit is not yet made it to the release).
- The subnetwork I am using to build the image is a shared VPC

I'm happy to share more details on my setup as required to debug further.

Thanks!

**Comment by medb** [comment]
https://github.com/GoogleCloudPlatform/cloud-dataproc/pull/75 PR that addresses this issue was merged.
