### ISSUE TITLE
line 37: run.sh: syntax error: invalid arithmetic operator (error token is ".sh")

### ISSUE THREAD

**Issue by YanzhongSu** [GoogleCloudPlatform/dataproc-custom-images#35]
Here is the command I used to create custom image:
```
python generate_custom_image.py \
    --image-name core-spark-conda-test \
    --dataproc-version 1.4.10-debian9 \
    --disk-size 50 \
    --customization-script ../start_actions.sh \
    --zone us-central1-f \
    --gcs-bucket gs://test-misc/dataproc-custom-image \
    --no-smoke-test
```

The start_actions.sh is [here](https://gist.github.com/YanzhongSu/e8fa775940deebd12d8a97f0fc2b5dc4).

It worked in July 2019 after this commit 49f33752bc83a135ce1d62875b02b270b5c1ed7d. Now I run it again on the latest commit, it gives me the following error:
```
+ echo 'Uploading files to GCS bucket.'
Uploading files to GCS bucket.
+ sources=([run.sh]='startup_script/run.sh' [init_actions.sh]='../init_actions.sh')
/var/folders/fr/hc45cptn3cs_hkf6y1zr7l7w0000gn/T/tmpQy24Bb: line 37: run.sh: syntax error: invalid arithmetic operator (error token is ".sh")
```

But when I roll back to this commit (49f33752bc83a135ce1d62875b02b270b5c1ed7d) It works. 

Does anyone know what causes this error and how to fix it?

**Comment by medb** [comment]
What bash version do you use?

May you post output of:
```bash
sh --version
bash --version
/usr/bin/bash --version
```

**Comment by aniket486** [comment]
This is most likely an issue due to version difference between /usr/bin/bash and bash in your environment.

**Comment by jason-huling** [comment]
I'm getting the same error, first time using it though...

I get the following version for `sh`, `bash`, and `/bin/bash`.
```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
```
 While `/usr/bin/bash --version` returns:
```
bash: /usr/bin/bash: No such file or directory
```

**Comment by medb** [comment]
@jason-huling You need to use bash 4, see [requirements](https://github.com/GoogleCloudPlatform/dataproc-custom-images#requirements) for more details.
